import { z } from 'zod';
import {
  AppointmentActionBody,
  AppointmentDetail,
  AppointmentList,
  AppointmentListQuery,
  CreateAppointmentBody,
  RescheduleAppointmentBody,
} from './appointments';
import { AuditListResponse } from './audit';
import {
  LoginBody,
  LoginResponse,
  MeResponse,
  MfaVerifyBody,
  OtpRequestBody,
  OtpRequestResponse,
  OtpVerifyBody,
  RefreshBody,
  TokenResponse,
} from './auth';
import {
  Allergy,
  ConsultationRecord,
  ConsultationView,
  CreateAllergyBody,
  CreateConditionBody,
  CreateMedicationBody,
  CurrentMedication,
  MedicalCondition,
  PatientChart,
  RemoveChartEntryBody,
  SaveConsultationBody,
  Vitals,
  VitalsBody,
  VitalsResponse,
} from './consultations';
import {
  Bill,
  BillView,
  CollectionsQuery,
  CollectionsReport,
  CreatePriceListItemBody,
  Payment,
  PriceList,
  PriceListItem,
  Receipt,
  RecordPaymentBody,
  SaveBillBody,
  UpdatePriceListItemBody,
} from './billing';
import { ErrorResponse } from './errors';
import {
  LastPrescription,
  LastPrescriptionQuery,
  MedicineList,
  MedicineQuery,
  Prescription,
  PrescriptionTemplate,
  PrescriptionTemplateList,
  PrescriptionView,
  SafetyActionBody,
  SafetySummary,
  SavePrescriptionBody,
  SaveTemplateBody,
  AmendPrescriptionBody,
  DoctorProfile,
  PrescriptionCheck,
  SaveDoctorProfileBody,
  SetSigningPinBody,
  SignPrescriptionBody,
  VerifyPrescriptionBody,
  VoidPrescriptionBody,
} from './prescriptions';
import {
  AcceptInviteBody,
  AcceptInviteResponse,
  CompleteInviteBody,
  CreateStaffInviteBody,
  CreatedStaffInvite,
  InviteDetails,
  InviteTokenBody,
  ResetAuthenticatorBody,
  StaffInviteList,
  StaffMemberList,
} from './invites';
import { HealthResponse } from './health';
import { CursorQuery } from './pagination';
import {
  CreatePatientBody,
  DuplicateCheckBody,
  DuplicateCheckResponse,
  PatientDetail,
  PatientListQuery,
  PatientListResponse,
  SetPatientTagsBody,
  UhidSettings,
  UpdatePatientBody,
  UpdateUhidSettingsBody,
} from './patients';
import {
  AvailabilityException,
  AvailabilityExceptionList,
  AvailabilityExceptionQuery,
  AvailabilityQuery,
  AvailabilityVersion,
  AvailabilityVersionList,
  BookingRules,
  Clinic,
  ClinicList,
  ConsultationType,
  ConsultationTypeList,
  CreateAvailabilityExceptionBody,
  CreateAvailabilityVersionBody,
  CreateClinicBody,
  CreateConsultationTypeBody,
  DoctorList,
  SlotsQuery,
  SlotsResponse,
  UpdateClinicBody,
  UpdateConsultationTypeBody,
} from './scheduling';
import {
  CreateDisplayScreenBody,
  CreatedDisplayScreen,
  DisplayBoard,
  DisplayScreenList,
  DisplayTokenBody,
  QueueQuery,
  QueueResponse,
} from './queue';
import { CreateTagBody, Tag, TagList, UpdateTagBody } from './tags';

interface Operation {
  method: 'get' | 'post' | 'put' | 'patch' | 'delete';
  path: string;
  operationId: string;
  summary: string;
  /** Endpoints without auth are listed explicitly; everything else needs a bearer token. */
  public?: boolean;
  body?: z.ZodType;
  query?: z.ZodObject;
  pathParams?: string[];
  response?: z.ZodType;
  /** Success status; defaults to 200. 204 has no body. */
  status?: 200 | 201 | 204;
  /** The response is a PDF file instead of JSON. */
  pdf?: boolean;
  /** For a 201 that a retry answers with 200 and the same body: what that 200 means. */
  replay?: string;
}

/** Every endpoint, in one list. Field detail always comes from the Zod schemas. */
const operations: Operation[] = [
  {
    method: 'get',
    path: '/health',
    operationId: 'getHealth',
    summary: 'Service health',
    public: true,
    response: HealthResponse,
  },
  {
    method: 'post',
    path: '/auth/otp/request',
    operationId: 'requestOtp',
    summary: 'Send a sign-in code to a patient mobile',
    public: true,
    body: OtpRequestBody,
    response: OtpRequestResponse,
  },
  {
    method: 'post',
    path: '/auth/otp/verify',
    operationId: 'verifyOtp',
    summary: 'Exchange a sign-in code for tokens',
    public: true,
    body: OtpVerifyBody,
    response: TokenResponse,
  },
  {
    method: 'post',
    path: '/auth/login',
    operationId: 'login',
    summary: 'Staff password step',
    public: true,
    body: LoginBody,
    response: LoginResponse,
  },
  {
    method: 'post',
    path: '/auth/mfa/verify',
    operationId: 'verifyMfa',
    summary: 'Staff authenticator-code step',
    public: true,
    body: MfaVerifyBody,
    response: TokenResponse,
  },
  {
    method: 'post',
    path: '/auth/invites/inspect',
    operationId: 'inspectInvite',
    summary: 'Show who an invite is for',
    public: true,
    body: InviteTokenBody,
    response: InviteDetails,
  },
  {
    method: 'post',
    path: '/auth/invites/accept',
    operationId: 'acceptInvite',
    summary: 'Set or confirm the password for an invite',
    public: true,
    body: AcceptInviteBody,
    response: AcceptInviteResponse,
  },
  {
    method: 'post',
    path: '/auth/invites/complete',
    operationId: 'completeInvite',
    summary: 'Confirm the authenticator code and sign in',
    public: true,
    body: CompleteInviteBody,
    response: TokenResponse,
  },
  {
    method: 'post',
    path: '/auth/refresh',
    operationId: 'refreshTokens',
    summary: 'Rotate the refresh token',
    public: true,
    body: RefreshBody,
    response: TokenResponse,
  },
  {
    method: 'post',
    path: '/auth/logout',
    operationId: 'logout',
    summary: 'End this session',
    status: 204,
  },
  {
    method: 'get',
    path: '/me',
    operationId: 'getMe',
    summary: 'Signed-in user, organisation and role',
    response: MeResponse,
  },
  {
    method: 'get',
    path: '/patients',
    operationId: 'listPatients',
    summary: 'Search patients (staff)',
    query: PatientListQuery,
    response: PatientListResponse,
  },
  {
    method: 'get',
    path: '/patients/{id}',
    operationId: 'getPatient',
    summary: 'Patient demographics and family (staff; view is audited)',
    pathParams: ['id'],
    response: PatientDetail,
  },
  {
    method: 'post',
    path: '/patients',
    operationId: 'createPatient',
    summary:
      'Register a patient and assign the next UHID (front desk, doctor, clinic admin); 409 on likely duplicates unless allowDuplicate',
    body: CreatePatientBody,
    response: PatientDetail,
    status: 201,
  },
  {
    method: 'patch',
    path: '/patients/{id}',
    operationId: 'updatePatient',
    summary: 'Edit demographics (front desk, doctor, clinic admin)',
    pathParams: ['id'],
    body: UpdatePatientBody,
    response: PatientDetail,
  },
  {
    method: 'post',
    path: '/patients/duplicate-check',
    operationId: 'checkPatientDuplicates',
    summary: 'Find existing patients with the same phone and name, or name and date of birth',
    body: DuplicateCheckBody,
    response: DuplicateCheckResponse,
  },
  {
    method: 'put',
    path: '/patients/{id}/tags',
    operationId: 'setPatientTags',
    summary: 'Replace a patient’s tags (front desk, doctor)',
    pathParams: ['id'],
    body: SetPatientTagsBody,
    response: PatientDetail,
  },
  {
    method: 'get',
    path: '/tags',
    operationId: 'listTags',
    summary: 'Tags configured for this organisation (staff)',
    response: TagList,
  },
  {
    method: 'post',
    path: '/tags',
    operationId: 'createTag',
    summary: 'Add a tag (clinic admin)',
    body: CreateTagBody,
    response: Tag,
    status: 201,
  },
  {
    method: 'patch',
    path: '/tags/{id}',
    operationId: 'updateTag',
    summary: 'Rename, recolour, archive or restore a tag (clinic admin)',
    pathParams: ['id'],
    body: UpdateTagBody,
    response: Tag,
  },
  {
    method: 'post',
    path: '/tags/defaults',
    operationId: 'addDefaultTags',
    summary: 'Add the default tags that are missing (clinic admin)',
    response: TagList,
  },
  {
    method: 'get',
    path: '/uhid-settings',
    operationId: 'getUhidSettings',
    summary: 'UHID prefix and next number (staff)',
    response: UhidSettings,
  },
  {
    method: 'put',
    path: '/uhid-settings',
    operationId: 'updateUhidSettings',
    summary: 'Set the UHID prefix and next number (clinic admin)',
    body: UpdateUhidSettingsBody,
    response: UhidSettings,
  },
  {
    method: 'get',
    path: '/clinics',
    operationId: 'listClinics',
    summary: 'Clinics (consulting locations) of this organisation (staff)',
    response: ClinicList,
  },
  {
    method: 'post',
    path: '/clinics',
    operationId: 'createClinic',
    summary: 'Add a clinic (clinic admin)',
    body: CreateClinicBody,
    response: Clinic,
    status: 201,
  },
  {
    method: 'patch',
    path: '/clinics/{id}',
    operationId: 'updateClinic',
    summary: 'Rename, edit or deactivate a clinic (clinic admin)',
    pathParams: ['id'],
    body: UpdateClinicBody,
    response: Clinic,
  },
  {
    method: 'get',
    path: '/consultation-types',
    operationId: 'listConsultationTypes',
    summary: 'Consultation types with fees in paise (staff)',
    response: ConsultationTypeList,
  },
  {
    method: 'post',
    path: '/consultation-types',
    operationId: 'createConsultationType',
    summary: 'Add a consultation type (clinic admin)',
    body: CreateConsultationTypeBody,
    response: ConsultationType,
    status: 201,
  },
  {
    method: 'patch',
    path: '/consultation-types/{id}',
    operationId: 'updateConsultationType',
    summary: 'Edit or deactivate a consultation type (clinic admin)',
    pathParams: ['id'],
    body: UpdateConsultationTypeBody,
    response: ConsultationType,
  },
  {
    method: 'get',
    path: '/booking-rules',
    operationId: 'getBookingRules',
    summary: 'Booking horizon and same-day cutoff (staff)',
    response: BookingRules,
  },
  {
    method: 'put',
    path: '/booking-rules',
    operationId: 'updateBookingRules',
    summary: 'Set the booking horizon and same-day cutoff (clinic admin)',
    body: BookingRules,
    response: BookingRules,
  },
  {
    method: 'get',
    path: '/doctors',
    operationId: 'listDoctors',
    summary: 'Active doctors in this organisation (staff)',
    response: DoctorList,
  },
  {
    method: 'get',
    path: '/availability/versions',
    operationId: 'listAvailabilityVersions',
    summary: 'Weekly schedule versions (staff)',
    query: AvailabilityQuery,
    response: AvailabilityVersionList,
  },
  {
    method: 'post',
    path: '/availability/versions',
    operationId: 'createAvailabilityVersion',
    summary: 'Set a weekly schedule from a date (the doctor, or a clinic admin)',
    body: CreateAvailabilityVersionBody,
    response: AvailabilityVersion,
    status: 201,
  },
  {
    method: 'delete',
    path: '/availability/versions/{id}',
    operationId: 'deleteAvailabilityVersion',
    summary: 'Withdraw a schedule version that has not started yet (the doctor, or a clinic admin)',
    pathParams: ['id'],
    status: 204,
  },
  {
    method: 'get',
    path: '/availability/exceptions',
    operationId: 'listAvailabilityExceptions',
    summary: 'Leave, holidays and extra sessions (staff)',
    query: AvailabilityExceptionQuery,
    response: AvailabilityExceptionList,
  },
  {
    method: 'post',
    path: '/availability/exceptions',
    operationId: 'createAvailabilityException',
    summary:
      'Add leave or an extra session (the doctor, or a clinic admin) or a holiday (clinic admin)',
    body: CreateAvailabilityExceptionBody,
    response: AvailabilityException,
    status: 201,
  },
  {
    method: 'delete',
    path: '/availability/exceptions/{id}',
    operationId: 'deleteAvailabilityException',
    summary: 'Remove leave, a holiday or an extra session that has not started yet',
    pathParams: ['id'],
    status: 204,
  },
  {
    method: 'get',
    path: '/slots',
    operationId: 'listSlots',
    summary: 'Slots for a doctor, clinic and consultation type on one day (staff)',
    query: SlotsQuery,
    response: SlotsResponse,
  },
  {
    method: 'get',
    path: '/appointments',
    operationId: 'listAppointments',
    summary: 'A day’s appointments (default today, IST) or one patient’s (staff)',
    query: AppointmentListQuery,
    response: AppointmentList,
  },
  {
    method: 'post',
    path: '/appointments',
    operationId: 'createAppointment',
    summary: 'Book a slot, overbook, or add a walk-in (front desk, doctor, clinic admin)',
    body: CreateAppointmentBody,
    response: AppointmentDetail,
    status: 201,
  },
  {
    method: 'get',
    path: '/appointments/{id}',
    operationId: 'getAppointment',
    summary: 'An appointment with its status history (staff)',
    pathParams: ['id'],
    response: AppointmentDetail,
  },
  {
    method: 'post',
    path: '/appointments/{id}/actions',
    operationId: 'actOnAppointment',
    summary: 'Confirm, check in, start, complete, cancel or mark no-show',
    pathParams: ['id'],
    body: AppointmentActionBody,
    response: AppointmentDetail,
  },
  {
    method: 'post',
    path: '/appointments/{id}/reschedule',
    operationId: 'rescheduleAppointment',
    summary: 'Move to another slot; returns the new appointment (front desk, doctor, clinic admin)',
    pathParams: ['id'],
    body: RescheduleAppointmentBody,
    response: AppointmentDetail,
    status: 201,
  },
  {
    method: 'get',
    path: '/patients/{id}/chart',
    operationId: 'getPatientChart',
    summary: 'Allergies, conditions, current medicines and recent visits (doctor)',
    pathParams: ['id'],
    response: PatientChart,
  },
  {
    method: 'post',
    path: '/patients/{id}/allergies',
    operationId: 'addAllergy',
    summary: 'Record an allergy (doctor)',
    pathParams: ['id'],
    body: CreateAllergyBody,
    response: Allergy,
    status: 201,
  },
  {
    method: 'post',
    path: '/patients/{id}/allergies/{entryId}/remove',
    operationId: 'removeAllergy',
    summary: 'Remove an allergy with a reason; the entry is kept (doctor)',
    pathParams: ['id', 'entryId'],
    body: RemoveChartEntryBody,
    status: 204,
  },
  {
    method: 'post',
    path: '/patients/{id}/conditions',
    operationId: 'addCondition',
    summary: 'Record a condition (doctor)',
    pathParams: ['id'],
    body: CreateConditionBody,
    response: MedicalCondition,
    status: 201,
  },
  {
    method: 'post',
    path: '/patients/{id}/conditions/{entryId}/remove',
    operationId: 'removeCondition',
    summary: 'Remove a condition with a reason; the entry is kept (doctor)',
    pathParams: ['id', 'entryId'],
    body: RemoveChartEntryBody,
    status: 204,
  },
  {
    method: 'post',
    path: '/patients/{id}/medications',
    operationId: 'addMedication',
    summary: 'Record a current medicine (doctor)',
    pathParams: ['id'],
    body: CreateMedicationBody,
    response: CurrentMedication,
    status: 201,
  },
  {
    method: 'post',
    path: '/patients/{id}/medications/{entryId}/remove',
    operationId: 'removeMedication',
    summary: 'Remove a current medicine with a reason; the entry is kept (doctor)',
    pathParams: ['id', 'entryId'],
    body: RemoveChartEntryBody,
    status: 204,
  },
  {
    method: 'get',
    path: '/appointments/{id}/vitals',
    operationId: 'getVitals',
    summary: 'Vitals recorded for a visit (front desk, doctor)',
    pathParams: ['id'],
    response: VitalsResponse,
  },
  {
    method: 'put',
    path: '/appointments/{id}/vitals',
    operationId: 'saveVitals',
    summary: 'Record or update a visit’s vitals (front desk, doctor)',
    pathParams: ['id'],
    body: VitalsBody,
    response: Vitals,
  },
  {
    method: 'get',
    path: '/appointments/{id}/consultation',
    operationId: 'getConsultation',
    summary: 'The consultation screen for a visit: appointment, notes and vitals (doctor)',
    pathParams: ['id'],
    response: ConsultationView,
  },
  {
    method: 'put',
    path: '/appointments/{id}/consultation',
    operationId: 'saveConsultation',
    summary: 'Save the consultation notes; rejects a stale revision (the visit’s doctor)',
    pathParams: ['id'],
    body: SaveConsultationBody,
    response: ConsultationRecord,
  },
  {
    method: 'get',
    path: '/medicines',
    operationId: 'searchMedicines',
    summary: 'Search the medicine master by name, generic or composition (doctor)',
    query: MedicineQuery,
    response: MedicineList,
  },
  {
    method: 'get',
    path: '/appointments/{id}/prescription',
    operationId: 'getPrescription',
    summary: 'A visit’s prescription draft (doctor)',
    pathParams: ['id'],
    response: PrescriptionView,
  },
  {
    method: 'put',
    path: '/appointments/{id}/prescription',
    operationId: 'savePrescription',
    summary: 'Save the prescription lines; rejects a stale revision (the visit’s doctor)',
    pathParams: ['id'],
    body: SavePrescriptionBody,
    response: Prescription,
  },
  {
    method: 'post',
    path: '/appointments/{id}/prescription/safety-actions',
    operationId: 'actOnSafetyAlert',
    summary: 'Acknowledge a safety warning or override an overridable block (the visit’s doctor)',
    pathParams: ['id'],
    body: SafetyActionBody,
    response: SafetySummary,
  },
  {
    method: 'get',
    path: '/appointments/{id}/prescription/preview',
    operationId: 'previewPrescriptionPdf',
    summary: 'The draft as a PDF marked PREVIEW, before signing (doctor)',
    pathParams: ['id'],
    pdf: true,
  },
  {
    method: 'post',
    path: '/appointments/{id}/prescription/sign',
    operationId: 'signPrescription',
    summary: 'Sign the draft with the signing PIN: re-checked, rendered, signed and locked',
    pathParams: ['id'],
    body: SignPrescriptionBody,
    response: Prescription,
  },
  {
    method: 'post',
    path: '/appointments/{id}/prescription/amend',
    operationId: 'amendPrescription',
    summary: 'Start the next version of a signed prescription, with a reason (the visit’s doctor)',
    pathParams: ['id'],
    body: AmendPrescriptionBody,
    response: Prescription,
    status: 201,
  },
  {
    method: 'post',
    path: '/appointments/{id}/prescription/void',
    operationId: 'voidPrescription',
    summary: 'Void the signed prescription with a reason and the signing PIN',
    pathParams: ['id'],
    body: VoidPrescriptionBody,
    response: Prescription,
  },
  {
    method: 'get',
    path: '/prescriptions/{id}/pdf',
    operationId: 'getPrescriptionPdf',
    summary: 'A signed version’s PDF (the copy marked VOID once voided); doctor or front desk',
    pathParams: ['id'],
    pdf: true,
  },
  {
    method: 'post',
    path: '/verify',
    operationId: 'verifyPrescription',
    summary: 'Check a prescription from its QR code: Genuine, Superseded or Void',
    public: true,
    body: VerifyPrescriptionBody,
    response: PrescriptionCheck,
  },
  {
    method: 'get',
    path: '/doctor-profile',
    operationId: 'getDoctorProfile',
    summary: 'The signed-in doctor’s prescription pad and signing details',
    response: DoctorProfile,
  },
  {
    method: 'put',
    path: '/doctor-profile',
    operationId: 'saveDoctorProfile',
    summary: 'Save registration, qualifications, prefix and paper size (doctor)',
    body: SaveDoctorProfileBody,
    response: DoctorProfile,
  },
  {
    method: 'put',
    path: '/doctor-profile/signing-pin',
    operationId: 'setSigningPin',
    summary: 'Set or change the signing PIN, confirmed with the account password',
    body: SetSigningPinBody,
    status: 204,
  },
  {
    method: 'get',
    path: '/patients/{id}/last-prescription',
    operationId: 'getLastPrescription',
    summary: 'The patient’s most recent earlier prescription, for Repeat last (doctor)',
    pathParams: ['id'],
    query: LastPrescriptionQuery,
    response: LastPrescription,
  },
  {
    method: 'get',
    path: '/prescription-templates',
    operationId: 'listPrescriptionTemplates',
    summary: 'The signed-in doctor’s prescription templates',
    response: PrescriptionTemplateList,
  },
  {
    method: 'post',
    path: '/prescription-templates',
    operationId: 'savePrescriptionTemplate',
    summary: 'Save lines as a template; the same name replaces it (doctor)',
    body: SaveTemplateBody,
    response: PrescriptionTemplate,
    status: 201,
  },
  {
    method: 'delete',
    path: '/prescription-templates/{id}',
    operationId: 'deletePrescriptionTemplate',
    summary: 'Delete one of your templates (doctor)',
    pathParams: ['id'],
    status: 204,
  },
  {
    method: 'get',
    path: '/price-list',
    operationId: 'listPriceList',
    summary: 'The clinic’s price list, active and inactive (staff)',
    response: PriceList,
  },
  {
    method: 'post',
    path: '/price-list',
    operationId: 'createPriceListItem',
    summary: 'Add a chargeable item (clinic admin)',
    body: CreatePriceListItemBody,
    response: PriceListItem,
    status: 201,
  },
  {
    method: 'patch',
    path: '/price-list/{id}',
    operationId: 'updatePriceListItem',
    summary: 'Rename, reprice or deactivate an item; bills keep the old price (clinic admin)',
    pathParams: ['id'],
    body: UpdatePriceListItemBody,
    response: PriceListItem,
  },
  {
    method: 'get',
    path: '/appointments/{id}/bill',
    operationId: 'getBill',
    summary: 'A visit’s bill with its payments, and the fees it can use (staff)',
    pathParams: ['id'],
    response: BillView,
  },
  {
    method: 'put',
    path: '/appointments/{id}/bill',
    operationId: 'saveBill',
    summary:
      'Create or replace the visit’s bill; the server prices every line; fixed after the first payment (front desk, doctor)',
    pathParams: ['id'],
    body: SaveBillBody,
    response: Bill,
  },
  {
    method: 'post',
    path: '/bills/{id}/payments',
    operationId: 'recordPayment',
    summary:
      'Record a counter payment (cash, UPI, card) with its receipt number; repeating the same payment ID returns it (front desk, doctor)',
    pathParams: ['id'],
    body: RecordPaymentBody,
    response: Payment,
    status: 201,
    replay: 'The payment was already recorded under this ID',
  },
  {
    method: 'get',
    path: '/payments/{id}/receipt',
    operationId: 'getReceipt',
    summary: 'A payment’s receipt, for printing (staff)',
    pathParams: ['id'],
    response: Receipt,
  },
  {
    method: 'get',
    path: '/collections',
    operationId: 'getCollections',
    summary: 'A day’s collections by mode and doctor, with the visits still due (staff)',
    query: CollectionsQuery,
    response: CollectionsReport,
  },
  {
    method: 'get',
    path: '/queue',
    operationId: 'getQueue',
    summary: 'A day’s queue grouped by tab: My OPD, Booked, Completed, Closed (staff)',
    query: QueueQuery,
    response: QueueResponse,
  },
  {
    method: 'get',
    path: '/display-screens',
    operationId: 'listDisplayScreens',
    summary: 'Active waiting-room screens (clinic admin)',
    response: DisplayScreenList,
  },
  {
    method: 'post',
    path: '/display-screens',
    operationId: 'createDisplayScreen',
    summary: 'Create a waiting-room screen link; the link is shown once (clinic admin)',
    body: CreateDisplayScreenBody,
    response: CreatedDisplayScreen,
    status: 201,
  },
  {
    method: 'post',
    path: '/display-screens/{id}/revoke',
    operationId: 'revokeDisplayScreen',
    summary: 'Stop a waiting-room screen link working (clinic admin)',
    pathParams: ['id'],
    status: 204,
  },
  {
    method: 'post',
    path: '/display/board',
    operationId: 'getDisplayBoard',
    summary: 'Current and next tokens for a waiting-room screen; no names (screen token)',
    public: true,
    body: DisplayTokenBody,
    response: DisplayBoard,
  },
  {
    method: 'post',
    path: '/staff/invites',
    operationId: 'createStaffInvite',
    summary: 'Invite a staff member (clinic admin)',
    body: CreateStaffInviteBody,
    response: CreatedStaffInvite,
    status: 201,
  },
  {
    method: 'get',
    path: '/staff/invites',
    operationId: 'listStaffInvites',
    summary: 'Recent staff invites (clinic admin)',
    response: StaffInviteList,
  },
  {
    method: 'post',
    path: '/staff/invites/{id}/revoke',
    operationId: 'revokeStaffInvite',
    summary: 'Revoke a pending invite (clinic admin)',
    pathParams: ['id'],
    status: 204,
  },
  {
    method: 'get',
    path: '/staff/members',
    operationId: 'listStaffMembers',
    summary: 'Staff in this organisation (clinic admin)',
    response: StaffMemberList,
  },
  {
    method: 'post',
    path: '/staff/members/{id}/reset-authenticator',
    operationId: 'resetAuthenticator',
    summary:
      'Reset a staff member’s password and authenticator; returns a new setup link (clinic admin)',
    pathParams: ['id'],
    body: ResetAuthenticatorBody,
    response: CreatedStaffInvite,
    status: 201,
  },
  {
    method: 'get',
    path: '/audit-log',
    operationId: 'listAuditLog',
    summary: 'Audit log (clinic admin)',
    query: CursorQuery,
    response: AuditListResponse,
  },
];

const errorResponse = {
  description: 'Error',
  content: { 'application/json': { schema: { $ref: '#/components/schemas/ErrorResponse' } } },
};

export function buildOpenApiDocument(options: { version: string; serverUrl?: string }) {
  const paths: Record<string, Record<string, unknown>> = {};
  for (const op of operations) {
    const status = op.status ?? 200;
    const parameters = [
      ...(op.pathParams ?? []).map((name) => ({
        name,
        in: 'path',
        required: true,
        schema: { type: 'string', format: 'uuid' },
      })),
      ...queryParameters(op.query),
    ];
    paths[op.path] ??= {};
    paths[op.path]![op.method] = {
      operationId: op.operationId,
      summary: op.summary,
      ...(op.public ? { security: [] } : {}),
      ...(parameters.length ? { parameters } : {}),
      ...(op.body
        ? {
            requestBody: {
              required: true,
              content: { 'application/json': { schema: toSchema(op.body, 'input') } },
            },
          }
        : {}),
      responses: {
        [String(status)]: op.pdf
          ? {
              description: 'PDF',
              content: { 'application/pdf': { schema: { type: 'string', format: 'binary' } } },
            }
          : status === 204 || !op.response
            ? { description: 'No content' }
            : {
                description: status === 201 ? 'Created' : 'OK',
                content: { 'application/json': { schema: toSchema(op.response) } },
              },
        ...(op.replay && op.response
          ? {
              '200': {
                description: op.replay,
                content: { 'application/json': { schema: toSchema(op.response) } },
              },
            }
          : {}),
        default: errorResponse,
      },
    };
  }

  return {
    openapi: '3.1.0',
    info: { title: 'Digital Healthcare Platform API', version: options.version },
    servers: options.serverUrl ? [{ url: options.serverUrl }] : [],
    paths,
    components: {
      schemas: { ErrorResponse: toSchema(ErrorResponse) },
      securitySchemes: { bearerAuth: { type: 'http', scheme: 'bearer' } },
    },
    security: [{ bearerAuth: [] }],
  };
}

function queryParameters(query: z.ZodObject | undefined) {
  if (!query) return [];
  const schema = toSchema(query, 'input') as {
    properties?: Record<string, unknown>;
    required?: string[];
  };
  return Object.entries(schema.properties ?? {}).map(([name, prop]) => ({
    name,
    in: 'query',
    required: schema.required?.includes(name) ?? false,
    schema: prop,
  }));
}

/** JSON Schema 2020-12 (the dialect OpenAPI 3.1 uses), without the top-level `$schema`. */
function toSchema(schema: z.ZodType, io: 'input' | 'output' = 'output') {
  const { $schema: _schema, ...rest } = z.toJSONSchema(schema, { io, unrepresentable: 'any' });
  return rest;
}
