import { z } from 'zod';
import { Language } from './patients';

export const MedicineRoute = z.enum([
  'oral',
  'topical',
  'inhaled',
  'eye',
  'ear',
  'nasal',
  'injection',
  'other',
]);
export type MedicineRoute = z.infer<typeof MedicineRoute>;

export const DoseTiming = z.enum([
  'after_food',
  'before_food',
  'with_food',
  'empty_stomach',
  'bedtime',
]);
export type DoseTiming = z.infer<typeof DoseTiming>;

export const DurationUnit = z.enum(['days', 'weeks', 'months']);
export type DurationUnit = z.infer<typeof DurationUnit>;

// ---- Medicine master ----------------------------------------------------------------

export const Medicine = z.object({
  id: z.uuid(),
  name: z.string(),
  genericName: z.string(),
  composition: z.string(),
  form: z.string(),
  defaultRoute: MedicineRoute,
  /** `reference`: the platform master; `clinic`: added by this clinic. */
  source: z.enum(['reference', 'clinic']),
});
export type Medicine = z.infer<typeof Medicine>;

export const MedicineList = z.object({ data: z.array(Medicine) });
export type MedicineList = z.infer<typeof MedicineList>;

export const MedicineQuery = z.object({ q: z.string().trim().min(2).max(60) });
export type MedicineQuery = z.infer<typeof MedicineQuery>;

// ---- Prescription lines -------------------------------------------------------------

/** One step of a schedule; a tapering course has several, followed in order. */
export const DoseStep = z
  .object({
    dose: z.string().trim().max(60),
    /** `1-0-1` style (morning-afternoon-night[-bedtime]), a code (OD, BD, TDS, SOS…) or free text. */
    frequency: z.string().trim().max(60),
    durationValue: z.number().int().min(1).max(365).nullable(),
    durationUnit: DurationUnit.nullable(),
  })
  .refine((step) => step.durationValue === null || step.durationUnit !== null, {
    message: 'A duration needs a unit (days, weeks or months).',
    path: ['durationUnit'],
  });
export type DoseStep = z.infer<typeof DoseStep>;

const lineFields = {
  /** From the master; null for a free-text medicine (flagged as not in the master). */
  medicineId: z.uuid().nullable(),
  name: z.string().trim().min(1).max(200),
  composition: z.string().trim().max(300).nullable(),
  form: z.string().trim().max(40).nullable(),
  route: MedicineRoute.nullable(),
  timing: DoseTiming.nullable(),
  steps: z.array(DoseStep).min(1).max(6),
  quantity: z.string().trim().max(60).nullable(),
  instructions: z.string().trim().max(300).nullable(),
  /**
   * The printed sentence. Regenerated by the server unless `remarksEdited`. The limit is
   * `REMARKS_MAX` in @dhc/domain, which fits the longest generated remark.
   */
  remarks: z.string().trim().max(1200),
  remarksEdited: z.boolean(),
};

/** A line as templates and "repeat last" carry it (no ID; new IDs are made when applied). */
export const TemplateItem = z.object(lineFields);
export type TemplateItem = z.infer<typeof TemplateItem>;

/** A line on a prescription; the client chooses the ID (a random UUID) so edits keep it. */
export const PrescriptionItem = z.object({ id: z.uuid(), ...lineFields });
export type PrescriptionItem = z.infer<typeof PrescriptionItem>;

// ---- Safety engine (PRD §6.5) ---------------------------------------------------------

/** One alert from the safety engine, with what the doctor has done about it. */
export const SafetyAlert = z.object({
  /** Rule, line and subject: the same problem keeps its key, a different one gets a new key. */
  key: z.string(),
  /** A rule from docs/safety/safety-rule-catalogue.md, e.g. `SR-05`. */
  ruleId: z.string().regex(/^SR-\d{2}$/),
  severity: z.enum(['block', 'warn', 'info']),
  /** The line it is about; null for the whole prescription. */
  itemId: z.uuid().nullable(),
  /** A block the drug database allows overriding with a reason. */
  overridable: z.boolean(),
  /** Acknowledging (a warning) or overriding (a block) needs a typed reason. */
  reasonRequired: z.boolean(),
  /** Based on a patient-reported allergy, condition or medicine not yet verified (SR-21). */
  unverified: z.boolean(),
  /** Names and numbers for the screen's own wording (medicine, molecule, allergy…). */
  params: z.record(z.string(), z.union([z.string(), z.number()])),
  /** English, as stored in the safety log. */
  message: z.string(),
  action: z.enum(['acknowledged', 'overridden']).nullable(),
  reason: z.string().nullable(),
  actionAt: z.iso.datetime().nullable(),
});
export type SafetyAlert = z.infer<typeof SafetyAlert>;

export const SafetySummary = z.object({
  alerts: z.array(SafetyAlert),
  /** The reference drug data the checks used. */
  drugDatabaseVersion: z.string(),
  /** Blocks not overridden; signing stays disabled while any remain. */
  openBlocks: z.number().int().min(0),
  /** Warnings not yet acknowledged. */
  openWarnings: z.number().int().min(0),
});
export type SafetySummary = z.infer<typeof SafetySummary>;

export const SafetyActionBody = z
  .object({
    key: z.string().min(1).max(300),
    /** `acknowledge` a warning, or `override` a block the database allows overriding. */
    action: z.enum(['acknowledge', 'override']),
    reason: z.string().trim().max(300).nullable(),
  })
  .refine((b) => b.action !== 'override' || (b.reason ?? '') !== '', {
    message: 'An override needs a reason.',
    path: ['reason'],
  });
export type SafetyActionBody = z.infer<typeof SafetyActionBody>;

export const Prescription = z.object({
  id: z.uuid(),
  status: z.enum(['draft', 'signed', 'void']),
  language: Language,
  items: z.array(PrescriptionItem),
  /** Increases on every save; send it back so a stale tab cannot overwrite newer lines. */
  revision: z.number().int().positive(),
  updatedAt: z.iso.datetime(),
  /** The server's safety check of these lines (it runs on every save). */
  safety: SafetySummary,
});
export type Prescription = z.infer<typeof Prescription>;

export const PrescriptionView = z.object({
  /** Null until the doctor first saves a line. */
  prescription: Prescription.nullable(),
  /** The patient's language, used for remarks until the doctor picks another. */
  defaultLanguage: Language,
  /** True when the signed-in doctor may write it (their visit, checked in, not signed). */
  canEdit: z.boolean(),
});
export type PrescriptionView = z.infer<typeof PrescriptionView>;

export const SavePrescriptionBody = z.object({
  language: Language,
  items: z.array(PrescriptionItem).max(30),
  /** The revision this edit started from; 0 for the first save. */
  revision: z.number().int().min(0),
});
export type SavePrescriptionBody = z.infer<typeof SavePrescriptionBody>;

/** The patient's most recent earlier prescription, for "Repeat last". */
export const LastPrescription = z.object({
  last: z
    .object({
      appointmentId: z.uuid(),
      date: z.iso.date(),
      doctorName: z.string().nullable(),
      items: z.array(TemplateItem),
    })
    .nullable(),
});
export type LastPrescription = z.infer<typeof LastPrescription>;

export const LastPrescriptionQuery = z.object({ before: z.uuid().optional() });
export type LastPrescriptionQuery = z.infer<typeof LastPrescriptionQuery>;

// ---- Templates ----------------------------------------------------------------------

export const PrescriptionTemplate = z.object({
  id: z.uuid(),
  name: z.string(),
  items: z.array(TemplateItem),
  updatedAt: z.iso.datetime(),
});
export type PrescriptionTemplate = z.infer<typeof PrescriptionTemplate>;

export const PrescriptionTemplateList = z.object({ data: z.array(PrescriptionTemplate) });
export type PrescriptionTemplateList = z.infer<typeof PrescriptionTemplateList>;

/** Saving under an existing name replaces that template. */
export const SaveTemplateBody = z.object({
  name: z.string().trim().min(1).max(80),
  items: z.array(TemplateItem).min(1).max(30),
});
export type SaveTemplateBody = z.infer<typeof SaveTemplateBody>;
