import { z } from 'zod';
import { Language } from './patients';

export const MedicineRoute = z.enum([
  'oral',
  'topical',
  'inhaled',
  'eye',
  'ear',
  'nasal',
  'injection',
  'other',
]);
export type MedicineRoute = z.infer<typeof MedicineRoute>;

export const DoseTiming = z.enum([
  'after_food',
  'before_food',
  'with_food',
  'empty_stomach',
  'bedtime',
]);
export type DoseTiming = z.infer<typeof DoseTiming>;

export const DurationUnit = z.enum(['days', 'weeks', 'months']);
export type DurationUnit = z.infer<typeof DurationUnit>;

// ---- Medicine master ----------------------------------------------------------------

export const Medicine = z.object({
  id: z.uuid(),
  name: z.string(),
  genericName: z.string(),
  composition: z.string(),
  form: z.string(),
  defaultRoute: MedicineRoute,
  /** `reference`: the platform master; `clinic`: added by this clinic. */
  source: z.enum(['reference', 'clinic']),
});
export type Medicine = z.infer<typeof Medicine>;

export const MedicineList = z.object({ data: z.array(Medicine) });
export type MedicineList = z.infer<typeof MedicineList>;

export const MedicineQuery = z.object({ q: z.string().trim().min(2).max(60) });
export type MedicineQuery = z.infer<typeof MedicineQuery>;

// ---- Prescription lines -------------------------------------------------------------

/** One step of a schedule; a tapering course has several, followed in order. */
export const DoseStep = z
  .object({
    dose: z.string().trim().max(60),
    /** `1-0-1` style (morning-afternoon-night[-bedtime]), a code (OD, BD, TDS, SOS…) or free text. */
    frequency: z.string().trim().max(60),
    durationValue: z.number().int().min(1).max(365).nullable(),
    durationUnit: DurationUnit.nullable(),
  })
  .refine((step) => step.durationValue === null || step.durationUnit !== null, {
    message: 'A duration needs a unit (days, weeks or months).',
    path: ['durationUnit'],
  });
export type DoseStep = z.infer<typeof DoseStep>;

const lineFields = {
  /** From the master; null for a free-text medicine (flagged as not in the master). */
  medicineId: z.uuid().nullable(),
  name: z.string().trim().min(1).max(200),
  composition: z.string().trim().max(300).nullable(),
  form: z.string().trim().max(40).nullable(),
  route: MedicineRoute.nullable(),
  timing: DoseTiming.nullable(),
  steps: z.array(DoseStep).min(1).max(6),
  quantity: z.string().trim().max(60).nullable(),
  instructions: z.string().trim().max(300).nullable(),
  /**
   * The printed sentence. Regenerated by the server unless `remarksEdited`. The limit is
   * `REMARKS_MAX` in @dhc/domain, which fits the longest generated remark.
   */
  remarks: z.string().trim().max(1200),
  remarksEdited: z.boolean(),
};

/** A line as templates and "repeat last" carry it (no ID; new IDs are made when applied). */
export const TemplateItem = z.object(lineFields);
export type TemplateItem = z.infer<typeof TemplateItem>;

/** A line on a prescription; the client chooses the ID (a random UUID) so edits keep it. */
export const PrescriptionItem = z.object({ id: z.uuid(), ...lineFields });
export type PrescriptionItem = z.infer<typeof PrescriptionItem>;

export const Prescription = z.object({
  id: z.uuid(),
  status: z.enum(['draft', 'signed', 'void']),
  language: Language,
  items: z.array(PrescriptionItem),
  /** Increases on every save; send it back so a stale tab cannot overwrite newer lines. */
  revision: z.number().int().positive(),
  updatedAt: z.iso.datetime(),
});
export type Prescription = z.infer<typeof Prescription>;

export const PrescriptionView = z.object({
  /** Null until the doctor first saves a line. */
  prescription: Prescription.nullable(),
  /** The patient's language, used for remarks until the doctor picks another. */
  defaultLanguage: Language,
  /** True when the signed-in doctor may write it (their visit, checked in, not signed). */
  canEdit: z.boolean(),
});
export type PrescriptionView = z.infer<typeof PrescriptionView>;

export const SavePrescriptionBody = z.object({
  language: Language,
  items: z.array(PrescriptionItem).max(30),
  /** The revision this edit started from; 0 for the first save. */
  revision: z.number().int().min(0),
});
export type SavePrescriptionBody = z.infer<typeof SavePrescriptionBody>;

/** The patient's most recent earlier prescription, for "Repeat last". */
export const LastPrescription = z.object({
  last: z
    .object({
      appointmentId: z.uuid(),
      date: z.iso.date(),
      doctorName: z.string().nullable(),
      items: z.array(TemplateItem),
    })
    .nullable(),
});
export type LastPrescription = z.infer<typeof LastPrescription>;

export const LastPrescriptionQuery = z.object({ before: z.uuid().optional() });
export type LastPrescriptionQuery = z.infer<typeof LastPrescriptionQuery>;

// ---- Templates ----------------------------------------------------------------------

export const PrescriptionTemplate = z.object({
  id: z.uuid(),
  name: z.string(),
  items: z.array(TemplateItem),
  updatedAt: z.iso.datetime(),
});
export type PrescriptionTemplate = z.infer<typeof PrescriptionTemplate>;

export const PrescriptionTemplateList = z.object({ data: z.array(PrescriptionTemplate) });
export type PrescriptionTemplateList = z.infer<typeof PrescriptionTemplateList>;

/** Saving under an existing name replaces that template. */
export const SaveTemplateBody = z.object({
  name: z.string().trim().min(1).max(80),
  items: z.array(TemplateItem).min(1).max(30),
});
export type SaveTemplateBody = z.infer<typeof SaveTemplateBody>;
